### ISSUE TITLE
'Please match the requested format' on CC # with spaces

### ISSUE THREAD

**Issue by jetlej** [wangjohn/creditly#7] opened 2014-05-23 17:41 UTC
By default the form automatically puts spaces between each group of 4 numbers in the credit card number. However this formatting continually gives me the error mentioned in the issue title unless I remove those spaces manually.

**Comment by chanceymathews** [comment] 2014-07-08 23:25
I had this issue too. It's actually a browser validation warning caused by the pattern='\d*' attribute on the form element (which is there in the example). I just removed the pattern attributes since Creditly does all that validation itself anyway, but I suppose you could change it to something like (\d+\s){3}\d+ and it would work too. It just needs to be a pattern that accepts the spaces Creditly is adding.

**Comment by wangjohn** [comment] 2014-07-09 04:52
Should be fixed by 6be0887b16539127a804b399b21a8cbea1e1a58d and 748e065c210ee49dfdbbd41f406063fc4a722cbc

**Comment by wangjohn** [comment] 2014-07-09 04:52
Thanks for bringing up the issue!

**Closed as completed by wangjohn** 2014-07-09 04:52 UTC
